title: "Lisa M. Simpson Resume"
description: "A resume for Lisa M. Simpson and GitHub Pages sites."
markdown: "kramdown"
sass:
  sass_dir: "_sass"
  style: "compressed"
resume_avatar: "true"
resume_name: "Lisa M. Simpson"
resume_contact_email: ""
resume_contact_telephone: ""
resume_contact_address: ""
resume_header_contact_info: ""
display_header_contact_info: "true"
resume_header_intro: "This is the executive summary. You should write a few brief, concise, and meaningful sentences about yourself from a professional context, and your immediate career goals. Make the length appropriate for your needs, but keep it brief and concise"
resume_looking_for_work: "yes"
resume_social_links:
  resume_github_url: "https://github.com/jglovier/resume-template"
  resume_linkedin_url: "https://www.linkedin.cn/incareer/in/joelglovier"
resume_print_social_links: True
resume_theme: "default"
resume_section_experience: True
resume_section_education: True
resume_section_projects: True
resume_section_skills: True
resume_section_recognitions: True
