
title: "郑尉欣 Resume"
description: "A resume for 郑尉欣 and GitHub Pages sites."
markdown: "kramdown"
sass: 
  sass_dir: "_sass"
  style: "compressed"
resume_avatar: "true"
resume_name: "郑尉欣"
resume_contact_email: "1979803044@qq.com"
resume_contact_telephone: "18617857316"
resume_contact_address: "浙江理工大学"
resume_header_contact_info: "浙江理工大学 • 18617857316 • 1979803044@qq.com"
display_header_contact_info: "true"
resume_header_intro: ""
resume_looking_for_work: "yes"
resume_social_links: 
  resume_github_url: "https://github.com/zweix123"
  resume_linkedin_url: ""
resume_print_social_links: True
resume_theme: "default"
resume_section_education: True
resume_section_recognitions: True
resume_section_experience: True
resume_section_projects: True
resume_section_skills: True
