description: A resume for 郑尉欣 and GitHub Pages sites.
resume_contact_address: 浙江理工大学
resume_contact_email: 1979803044@qq.com
resume_contact_telephone: '18617857316'
resume_header_contact_info: 浙江理工大学 • 18617857316 • 1979803044@qq.com
resume_header_intro: ''
resume_name: 郑尉欣
resume_social_links:
  resume_github_url: github.com/zweix123
  resume_linkedin_url: ''
title: 郑尉欣 Resume
